## SpriteFactory — loads pixel-art sprites from committed PNG assets and
## hands out cached Texture2Ds. Every visible sprite in the game is
## authored by `generate_sprites.py` at the project root and saved into
## `godot/assets/sprites/`. SpriteFactory is a thin loader + slicer layer.
##
## Asset layout (generated by generate_sprites.py):
##
##   godot/assets/sprites/
##     anim/pieces/<color>/<piece_id>/<anim>.png   (horizontal frame strip)
##     anim/fx/<kind>.png                          (horizontal frame strip)
##     tiles/<stage>/<light|dark>.png              (single tile)
##     ui/energy_<filled|empty>.png                (single segment)
##     ui/ability_<cannon|lightning>.png           (single icon)
##     ui/shadow.png                               (drop shadow)
##
## Animation strips are sliced into per-frame ImageTextures via
## Image.load_from_file → blit_rect, which works with raw PNGs regardless
## of Godot's import state (no .import sidecar required).
class_name SpriteFactory
extends RefCounted

const ASSET_ROOT := "res://assets/sprites"

static var _cache: Dictionary = {}

# ===========================================================================
# PIECE SPRITES
# ===========================================================================

static func piece_texture(piece_id: String, color: int) -> Texture2D:
	var key := "piece:%s:%d" % [piece_id, color]
	if _cache.has(key): return _cache[key]
	var path := "%s/anim/pieces/%s/%s/static.png" % [ASSET_ROOT, _color_dir(color), piece_id]
	var arr := _load_strip(path)
	var tex: Texture2D = arr[0] if arr.size() > 0 else null
	_cache[key] = tex
	return tex

## Alias kept for the customization preview / ability target previews. Size
## is set by the receiving TextureRect; the cached static texture is reused.
static func piece_texture_size(piece_id: String, color: int, _native: int) -> Texture2D:
	return piece_texture(piece_id, color)

## Per-(id, color) animation map. Keys present:
##   "static"        — single Texture2D (also the sprite's idle frame)
##   "move", "attack", "hit", "death" — Array[Texture2D]
##   "move_jump"     — Array[Texture2D] (knight + alter_knight only)
##   "attack_lunge"  — Array[Texture2D] (alter_knight only)
##
## Animations whose strip file is missing are simply absent from the dict —
## callers should `dict.has(anim)` before reading.
static func piece_frames(piece_id: String, color: int) -> Dictionary:
	var key := "piece_frames:%s:%d" % [piece_id, color]
	if _cache.has(key): return _cache[key]
	var dir := "%s/anim/pieces/%s/%s" % [ASSET_ROOT, _color_dir(color), piece_id]
	var out: Dictionary = {}
	out["static"] = piece_texture(piece_id, color)
	for anim in ["move", "attack", "hit", "death", "move_jump", "attack_lunge"]:
		var arr := _load_strip("%s/%s.png" % [dir, anim])
		if not arr.is_empty():
			out[anim] = arr
	_cache[key] = out
	return out

static func _color_dir(color: int) -> String:
	return "white" if color == 0 else "black"

## Translate a `res://`-style path to an absolute OS path. `Image` raw
## loaders only accept absolute paths; this lets us read PNGs straight off
## disk without depending on Godot's import system / .import sidecars.
static func _abs(path: String) -> String:
	return ProjectSettings.globalize_path(path) if path.begins_with("res://") else path

## Slice a horizontal frame strip PNG into Array[Texture2D]. Returns []
## when the file is missing or unreadable so callers can branch on
## `arr.is_empty()`. Square-frame assumption: each frame is `h x h`.
static func _load_strip(path: String) -> Array:
	if not FileAccess.file_exists(path):
		return []
	var img := Image.load_from_file(_abs(path))
	if img == null:
		return []
	var w := img.get_width()
	var h := img.get_height()
	if h <= 0 or w <= 0:
		return []
	var n := w / h
	var frames: Array = []
	for i in n:
		var f := Image.create(h, h, false, Image.FORMAT_RGBA8)
		f.blit_rect(img, Rect2i(i * h, 0, h, h), Vector2i.ZERO)
		frames.append(ImageTexture.create_from_image(f))
	return frames

## Load a single PNG as a Texture2D. Used for tiles and UI sprites where
## there's no frame slicing — the whole image is the texture. Returns null
## when the file is missing.
static func _load_single(path: String) -> Texture2D:
	if not FileAccess.file_exists(path):
		return null
	var img := Image.load_from_file(_abs(path))
	if img == null:
		return null
	return ImageTexture.create_from_image(img)

# ===========================================================================
# ABILITY / HAZARD FX
# ===========================================================================

static func cannon_resolve_frames() -> Array:
	var key := "fx:cannon_resolve"
	if _cache.has(key): return _cache[key]
	var f := _load_strip("%s/anim/fx/cannon_resolve.png" % ASSET_ROOT)
	_cache[key] = f
	return f

static func debris_fall_frames() -> Array:
	var key := "fx:debris_fall"
	if _cache.has(key): return _cache[key]
	var f := _load_strip("%s/anim/fx/debris_fall.png" % ASSET_ROOT)
	_cache[key] = f
	return f

static func lightning_strike_frames() -> Array:
	var key := "fx:lightning_strike"
	if _cache.has(key): return _cache[key]
	var f := _load_strip("%s/anim/fx/lightning_strike.png" % ASSET_ROOT)
	_cache[key] = f
	return f

static func aoe_resolve_frames(kind: String) -> Array:
	match kind:
		"cannon": return cannon_resolve_frames()
		"debris": return debris_fall_frames()
	return []

# ===========================================================================
# BOARD TILES
# ===========================================================================

static func tile_texture(is_dark: bool) -> Texture2D:
	return tile_texture_for_stage(is_dark, "classic")

static func tile_texture_for_stage(is_dark: bool, stage: String) -> Texture2D:
	var key := "tile:%s:%d" % [stage, 1 if is_dark else 0]
	if _cache.has(key): return _cache[key]
	var path := "%s/tiles/%s/%s.png" % [ASSET_ROOT, stage, "dark" if is_dark else "light"]
	var tex := _load_single(path)
	if tex == null:
		## Fallback to classic if a stage's assets are missing — keeps the
		## board visible during partial asset rolls.
		tex = _load_single("%s/tiles/classic/%s.png" % [ASSET_ROOT, "dark" if is_dark else "light"])
	_cache[key] = tex
	return tex

# ===========================================================================
# UI — energy segments, ability icons, drop shadow.
# ===========================================================================

static func energy_segment_texture(filled: bool) -> Texture2D:
	var key := "energy_seg:%d" % (1 if filled else 0)
	if _cache.has(key): return _cache[key]
	var path := "%s/ui/%s.png" % [ASSET_ROOT, "energy_filled" if filled else "energy_empty"]
	_cache[key] = _load_single(path)
	return _cache[key]

static func ability_icon_texture(kind: int) -> Texture2D:
	var key := "ability:%d" % kind
	if _cache.has(key): return _cache[key]
	## Map: SpecialAbilityDef.Kind.CANNON = 1, LIGHTNING = 2.
	var icon_name := ""
	if kind == 1:   icon_name = "ability_cannon"
	elif kind == 2: icon_name = "ability_lightning"
	var tex: Texture2D = null
	if icon_name != "":
		tex = _load_single("%s/ui/%s.png" % [ASSET_ROOT, icon_name])
	_cache[key] = tex
	return tex

static func shadow_texture() -> Texture2D:
	var key := "shadow"
	if _cache.has(key): return _cache[key]
	_cache[key] = _load_single("%s/ui/shadow.png" % ASSET_ROOT)
	return _cache[key]
